services:
  synset-monitor:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROCFS_PATH=/host/proc
      - HOST_ROOTFS=/rootfs
      - HOST_LOG_DIR=/host/var/log
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
